drop table rabaty,ulgi,uzytkownicy,konto,zamowienia,przewoznicy,stacje,trasy,stacje_posrednie,cennik_biletow_okresowych,bilety_okresowe_zamowienia,przejazdy,wagony,wagony_typy_miejsc,szczegoly_biletu,przejazdy_wagony,bilety_jednorazowe_zamowienia cascade ;

